### ISSUE TITLE
Setting up communication with the Raspberry Pi.

### ISSUE THREAD

**Issue by MwauratheAlex** [roboticsdojo/internship2023#52]
A communication link between the Raspberry pi has to be set up.
- If possible, I was thinking that the arm may need obstacle distance information from the ultrasonic sensor on the mobile platform.
- Another option would be adding another ultrasonic sensor for the arm.
- A simpler option would be pre-programming the mobile platform to always stop at a specified distance (x) from the objects to be picked.

**Comment by codewithlennylen** [comment]
- While it is simple to pre-program specific stop distances, we can't rely much on this due to accuracy issues.
- I advocate for an additional ultrasonic sensor for the arm but an even better alternative would be using a depth camera.
